name: CI
on: [push]
jobs:
  win:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: free up disk space
      run: ./free-disk-space.sh
    - name: add a wait so that the job starts
      run: sleep 10
    - name: wait for Windows disk cleanup to finish
      run: |
        python3 free-disk-space-windows-wait.py
